### ISSUE TITLE
illegal base32 data at input byte 24

### ISSUE THREAD

**Issue by ofinsterbusch** [itsmewes/gotp#3] opened 2021-02-03 17:32 UTC
Hello,

Great work and awesome Alfred integration. 

I have an error trying to use a key:

**Error**: illegal base32 data at input byte 24

Key is 27 characters.
In the otpauth url the period should be 30 and it have an issuer.

Is there any way to make this work?

Many thanks!

**Comment by itsmewes** [comment] 2021-02-04 06:16
Hi @ofinsterbusch,

Glad you're liking gotp so far 😊

Would you be able to give me some more information please? Sorry I'm not sure how to replicate the problem on my side to debug. Are you able to let me know what service you are using that is giving you the 27 character key? Hopefully I'll be able to reproduce the issue and be able to send out a fix.

**Comment by ofinsterbusch** [comment] 2021-02-04 08:25
Hi @itsmewes,

The service is bit defender gravity zone admin panel.

They url have this format: 

otpauth://totp/_my%40email.com_?secret=_SSECRETKEY2727272727272727_&period=30&digits=6&issuer=Gravity+Zone+Cloud

Thanks for checking it!

**Comment by itsmewes** [comment] 2021-02-04 15:25
Hi @ofinsterbusch 

I've been looking at the issue, to be honest I'm a bit out of my depth here, but I have taken an initial crack at it. Could you try it out and see if it makes any difference? I have uploaded it as a zip file since you can't upload binaries here. you'll need to add the key (SSECRETKEY2727272727272727) again. I don't think it'll give you an error now but I'm not confident that the output will be correct and accepted.
[gotp.zip](https://github.com/itsmewes/gotp/files/5926650/gotp.zip)

**Comment by ofinsterbusch** [comment] 2021-02-04 15:41
Hi @itsmewes,

Thanks a lot for the quick answer and fix. 

Now it's not giving any error but the code is not the correct one comparing to Google Authenticator. 
I think the problem is with the period as the normal period for codes is 60 seconds but this one is 30.

Do you think it can be something like that?

Many thanks again.

**Comment by ofinsterbusch** [comment] 2021-02-15 18:49
Hello @itsmewes,

I dig a bit more with other tools so I can provide some extra information.

Using oauthtool here is the command I used: oathtool --base32 SSECRETKEY2727272727272727 --digits=6 --totp

So it looks like this secret is based32 encoded and that's why is not working.

Question is if you can find a way of checkin if the secret is encoded or you need to add that option when adding a new key.

For me is working now with oauthtool and I did a workflow in Alfred only for this secret but maybe we want to add it to your command.

Thanks again for your work!

**Comment by jonnywilliamson** [comment] 2021-02-23 14:15
Hi. Similar issue here.

![image](https://user-images.githubusercontent.com/2513663/108855777-41628880-75e1-11eb-87a1-466c5aaf589d.png)


I cut off the full key, but it was 52 characters long and came from the website epicgames.com

What else can i provide to help? I don't really have any more info I'm afraid!

**Comment by itsmewes** [comment] 2021-02-23 16:38
Hi @jonnywilliamson 

Thanks for adding to the issue, might help with figuring out how to handle different types of keys.

@ofinsterbusch sorry I have gone dark, things have been crazy at work. 

I'll try take a look at these kinds of keys and hopefully be able to get an update out.

**Comment by itsmewes** [comment] 2021-02-23 16:53
@jonnywilliamson @ofinsterbusch 

Are you able to provide the actual keys that you had, sorry to ask but it's proving really hard to test this since I'm not 100% sure I'm able to get a code that matches how your keys are put together.

**Comment by jonnywilliamson** [comment] 2021-02-23 22:25
@itsmewes Sure thing, its not a website I'm overly concerned with.

What would be the best way to send the code to you. I'd rather at least do it directly. My email is my github username and gmail

**Comment by jonnywilliamson** [comment] 2021-02-23 22:28
Actually,

Why not just sign up the same website as I was dealing with? Just register and the in your account activate 2FA and you'll get the same type of code I was getting.

The direct URL for sign up to save you a few clicks is:

https://www.epicgames.com/id/register/epic?redirect_uri=https%3A%2F%2Fwww.epicgames.com%2Fstore%2Fen-US%2F&client_id=875a3b57d3a640a6b7f9b4e883463ab4

**Comment by itsmewes** [comment] 2021-04-15 13:37
@ofinsterbusch and @jonnywilliamson I think I cracked it. Sorry for it taking so long. If you are still using GOTP can you try the new release (0.7.0) and let me know if it works for you.

**Comment by ofinsterbusch** [comment] 2021-04-16 10:44
Hey, just tried it and I think is working now.

Many thanks! great job!

**Comment by itsmewes** [comment] 2021-05-01 10:11
Awesome, thanks for testing @ofinsterbusch, closing the issue 😊

**Closed as completed by itsmewes** 2021-05-01 10:11 UTC
